AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Role: arn:aws:iam::840152204631:role/AWS-CodePipeline-Service
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
